version: '3.8'

services:

  includia-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5201:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__MongoDb=mongodb://includia-mongo:27017
      - ConnectionStrings__OracleDb=USER ID=system;PASSWORD=admin;DATA SOURCE=includia-oracle:1521/XEPDB1
    depends_on:
      includia-mongo:
        condition: service_started
      includia-oracle:
        condition: service_healthy 

  includia-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 
    restart: unless-stopped

  includia-oracle:
    image: gvenzl/oracle-xe:latest
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=admin
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 50
    restart: unless-stopped

volumes:
  mongo-data:
  oracle-data: